### ISSUE TITLE
[PAGE] PR팀의 팀별 기여방안 포스팅 내용 추가 바람

### ISSUE THREAD

**Issue by kanghohyeong** [20-1-SKKU-OSS/2020-1-OSS-3#12]
페이지에 팀별 기여방안을 포스팅하였습니다.
PR팀은 PR팀의 기여방안을 정리하여 알려주시면 포스팅에 반영하겠습니다.

**Comment by mtm776** [comment]
1. 기존에 존재하는 채용공고 수정
(기간 지난 공고 삭제/영어버전 공고 수정)
2. 새로운 채용공고를 수집하여 추가
 (여러 회사들의 채용 정보들을 수집한 후 평점을 기준으로 하여 순차적으로 선별)
3. 작업에 필요한 이슈 지속적으로 작성
4. 미흡사항 개선 및 추가 기능 구현

**Comment by kanghohyeong** [comment]
추가하였습니다.
