### ISSUE TITLE
[PR] 채용공고 수집 2nd

### ISSUE THREAD

**Issue by hyeonjae-J** [20-1-SKKU-OSS/2020-1-OSS-3#13]
두번째 채용공고 사이트 모음 PR 입니다

**Comment by hyeonjae-J** [comment]
1. 네이버의 AI 프로젝트 인턴십 입니다.
http://m.site.naver.com/0xia7 

2. 크래프톤 채용 연계형 인턴십 입니다
https://krafton.recruiter.co.kr/app/jobnotice/view?systemKindCode=MRS2&jobnoticeSn=28496

3. 에이전트 소프트 채용공고
http://www.agentsoft.co.kr/recruit/noti.php

4.넥슨코리아 게임 프로그래머 채용공고
https://www.jobplanet.co.kr/companies/83498/job_postings/1158835/%EA%B5%AD%EB%82%B4%EB%A9%94%EC%9D%B4%ED%94%8C-%EA%B2%8C%EC%9E%84%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8-%EB%AA%A8%EC%A7%91/%EB%84%A5%EC%8A%A8%EC%BD%94%EB%A6%AC%EC%95%84?_rs_act=search&_rs_con=job_postings&_rs_element=search_result

5.네이버 예약 플랫폼 개발 채용연계형 인턴십
https://recruit.navercorp.com/naver/job/detail/developer?annoId=20004064&classId=&jobId=&entTypeCd=004&searchTxt=&searchSysComCd=

6. 네이버 Computer Vision Engineer (체험형 인턴)
https://recruit.navercorp.com/naver/job/detail/developer?annoId=20004058&classId=&jobId=&entTypeCd=004&searchTxt=&searchSysComCd=

**Comment by HyeonjinChoi** [comment]
2번은 오늘 오후 6시에 마감되었습니다.
5번은 기존 저장소에 이미 올라왔습니다.

**Comment by mtm776** [comment]
6번 채용공고가 저희가 채택한 공고 선택 기준에 부합한 것 같아서 추천합니다.

**Comment by hyeonjae-J** [comment]
1, 3, 6번 PR 보내보도록 하겠습니다.
