### ISSUE TITLE
[PR] 채용공고 수집 3rd

### ISSUE THREAD

**Issue by mtm776** [20-1-SKKU-OSS/2020-1-OSS-3#14]
<채용공고>

**Comment by mtm776** [comment]
1. [AI검색플랫폼] 서버, 머신러닝 개발자-카카오엔터프라이즈 ~6.30

2. 포털개발팀 웹 프론트엔드 프로그래머-넷마블컴퍼니 잼팟 ~ 상시채용

3. [Clova] AI Platform Ecosystem 개발자 신입/경력사원 모집-네이버 ~6.14

4. 파파고 머신러닝 엔지니어 신입/경력사원 모집-네이버 ~6.30

5. 풀스택 개발자-샌드박스네트워크 ~6.13

6. [AI LAB] COMPUTER VISION 리서치 엔지니어-버즈니 ~상시채용

**Comment by mtm776** [comment]
1번 채용공고의 마감기한은 12.31까지 입니다.

**Comment by mtm776** [comment]
1.https://kakaoenterprise.recruiter.co.kr/app/jobnotice/view?systemKindCode=MRS2&jobnoticeSn=17209
https://kakaoenterprise.recruiter.co.kr/app/jobnotice/view?systemKindCode=MRS2&jobnoticeSn=17061

2.https://programmers.co.kr/job_positions/1484

3.https://recruit.navercorp.com/naver/job/detail/developer?annoId=20004078&classId=&jobId=&entTypeCd=&searchTxt=&searchSysComCd=

4.https://recruit.navercorp.com/naver/job/detail/developer?annoId=20003164&classId=&jobId=&entTypeCd=&searchTxt=&searchSysComCd=

5.https://www.sandbox.co.kr/careers/sandbox/127

6.https://recruit.buzzni.com/recruit/ai-%ec%bb%b4%ed%93%a8%ed%84%b0%eb%b9%84%ec%a0%84-2004/

**Comment by HyeonjinChoi** [comment]
#5 샌드박스의 성장속도와 효율적인 협업 환경을 고려했을 때 추천할 만한 것 같습니다.

**Comment by HyeonjinChoi** [comment]
#5 샌드박스의 성장속도와 효율적인 협업 환경을 고려했을 때 추천할 만한 것 같습니다.

**Comment by HyeonjinChoi** [comment]
5번 채용공고가 샌드박스의 성장속도와 효율적인 협업 환경을 고려했을 때 추천할 만한 것 같습니다.
