### ISSUE TITLE
[PR] 채용공고 수집 5th

### ISSUE THREAD

**Issue by mtm776** [20-1-SKKU-OSS/2020-1-OSS-3#18]
채용공고 목록을 추가합니다.

**Comment by mtm776** [comment]
<해커톤>
제 8회 k-해커톤 실감콘텐츠 앱 개발 챌린지
<채용공고>
1.[상시]카카오 분석 플랫폼 개발자 모집(1년이상 5년미만)
주소:https://careers.kakao.com/jobs/P-11396
2.[202.6.8~2020.9.8] 네이버 AI기반 글로벌 추천 서비스/시스템 개발자 모집
주소:https://recruit.navercorp.com/naver/job/detail/developer?annoId=20004095&classId=&jobId=&entTypeCd=001&searchTxt=%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0&searchSysComCd=
3.[상시]넥슨 [인텔리전스랩스] 데이터인프라개발팀 모집
주소:https://career.nexon.com/user/recruit/notice/noticeView?joinCorp=NX&reNo=20200007
4.[상시] 클래스 101 웹 프론트엔드 개발자 모집(*github 계정 제출 권장)
주소:https://www.notion.so/1fa730f7383648329c1bae168bbd2fba
5.[상시] 이투스 Junior Web & Server Developer 모집(4년 미만)
주소:https://recruit.etoos.com/recruit/viewRecruitApply.do

**Comment by HyeonjinChoi** [comment]
5년정도의 경력직을 뽑지만 여러 복지혜택들이 우수한 것 같습니다.
4번 추천합니다.
